### PR TITLE
Fix readme/microsite

### PR DESCRIPTION
**Pull request by dzanot**
Fixes https://github.com/higherkindness/skeuomorph/issues/117

I just fixed for the current setup, but I have a feeling there's a better way to structure this though.
Maybe moving the tut readme into docs and having thing root readme just link to the microsite?

### CODE REVIEW

**Comment by pepegar** [comment]
Regarding your question... I'm not completely sure.  Currently we're using `readme/README.md` for both `README.md` in the root of the repo, and also for the `index.md` in docs.

Do you think we could enhance the process somehow?

**Comment by bilki** [comment]
I like the `protobuf` example but those definitions look kinda long compared to `avro` example, also it does not perform any typecheck with tut. Maybe we could use a reduced example, or go the other way and expand the `avro` example to match `protobuf` one?

**Comment by dzanot** [comment]
@bilki for those examples, I didn't add them I just moved them from one readme to the tut readme.

**Comment by dzanot** [comment]
I've condensed the protobuf example to mirror the Avro. I'd like to make it a little more complex by adding a service definition but I'm going to have to tinker to get it to work on the avro side. 

I've also trimmed down the root README, added a link to the microsite, and moved the examples into the docs submodule as `index.md`

**Comment by dzanot** [comment]
Happy to help, CI is all green but I don't have write permissions. Feel free to merge!

**Pull request merged**
