### PR TITLE
Exhaustive protobuf tests

### PR DESCRIPTION
**Pull request by AdrianRaFo**
This PR shows how protobuf serialization still has failures to be resolved:

**Everything on Proto3 should be optional and we are just generation as optional when using generated messages.**

As Proto2 is also converted to Proto3 we should take some design decisions about this. Also, I cannot find any way to generate an intentional optional with the current design.

**Nested messages classes are not generated. The `BookSeries` model inside the `Series` one is not generated.**

Due to this error, I realized that we are not generating and compiling the scala from the proto we are using. This would help us to detect more bugs in the generation

**Scala keywords are not quoted so scala generated code will not compile**

If we use a scala keyword as the name of a field the generator should quote it using **`** so the generated code can compile

### CODE REVIEW

**Comment by fedefernandez** [comment]
Would it make sense to add `ignored` to these tests and get that merged? @AdrianRaFo @juanpedromoreno @pepegar thoughts?

**Comment by AdrianRaFo** [comment]
I would not do that because we don't want to lose those tests on other PRs that can cause more issues

**Comment by juanpedromoreno** [comment]
Makes sense to me, @fedefernandez

**Comment by fedefernandez** [comment]
@AdrianRaFo the idea behind merging this is to avoid losing the code and to avoid maintaining the code. Once merged with the ignored keyword they will be seen as a warning, telling us that this is something to be fixed. Does it make sense?

**Comment by AdrianRaFo** [comment]
I think it's too late to do that so I'll close this

**Pull request closed without merging**
