### PR TITLE
explicit types needed for OpenApi json Aux implicits

### PR DESCRIPTION
**Pull request by JLofgren**
This change is required in order to compile generated code in scala 2.13.11. Without this the compiler errors with "Implicit definition should have explicit type"

I am really unfamiliar with skeuomorph, so am completely unprepared to propose a fix, but I know that this issue is breaking my use case currently.

### CODE REVIEW

**Comment by dzanot** [comment]
possible fix here https://github.com/JLofgren/skeuomorph/pull/1

**Comment by JLofgren** [comment]
Thanks very much, @dzanot !

**Comment by dzanot** [comment]
@rafaparadela @fedefernandez I still have maintainer status but don't want to merge without someone else approving, if you could take a look when you have a free moment please and thank you 🙏

**Review by juanpedromoreno — APPROVED** [review]

**Review by fedefernandez — APPROVED** [review]
LGTM @dzanot 
Thanks @JLofgren

**Pull request merged**
